### ISSUE TITLE
Truncut trims icon name away

### ISSUE THREAD

**Issue by LarsFlieger** [tailwindlabs/heroicons.com#131]
### Problem
Some Icons have too long names that they are getting displayed. 
![image](https://user-images.githubusercontent.com/47084064/186445755-80018340-17ae-4f46-bffd-36fad0ab02cd.png)

When you want to get the icons name you have to inspect the HTML code.

### Solution(s) / Ideas
- Add title attribute to view everything on hover: 
![image](https://user-images.githubusercontent.com/47084064/186446208-9e502cab-132f-4364-bfa0-f0bba79392b4.png)
- When you click on the text remove the `truncate` (like a "more..". button): 
![image](https://user-images.githubusercontent.com/47084064/186446456-a64a5b41-e753-4089-a5e6-0a6c9e2d2a69.png)

What solution do you think fit's better? I can create an PR.

**Comment by thecrypticace** [comment]
The icons already have a title attribute to show the full name on hover (added in PR #127 yesterday):

<img width="478" alt="Screen Shot 2022-08-24 at 13 07 23" src="https://user-images.githubusercontent.com/614993/186480710-abdb91ec-b0f3-4b7d-a57b-30cfe8208369.png">

If you want to select and copy the whole name you can usually do one of two things:
1. Triple click the icon name and then copy. This generally selects the whole, non-truncated string.
2. Click and drag from the beginning and move _down_. This wraps the selection to the end of the line and allows you to copy the entire icon name.

**Comment by LarsFlieger** [comment]
> The icons already have a title attribute to show the full name on hover (added in PR #127 yesterday):
> 
> <img alt="Screen Shot 2022-08-24 at 13 07 23" width="478" src="https://user-images.githubusercontent.com/614993/186480710-abdb91ec-b0f3-4b7d-a57b-30cfe8208369.png">
> 
> If you want to select and copy the whole name you can usually do one of two things:
> 
> 1. Triple click the icon name and then copy. This generally selects the whole, non-truncated string.
> 2. Click and drag from the beginning and move _down_. This wraps the selection to the end of the line and allows you to copy the entire icon name.

Great shortcut tip! Didn't know that :) Thank you!
