### ISSUE TITLE
Broken "Download All" link

### ISSUE THREAD

**Issue by jpinnix** [tailwindlabs/heroicons.com#15]
"Download All" is pointing to a URI that gives a 404: https://github.com/tailwindlabs/heroicons/archive/v0.4.1.zip

I assume that for some reason `${version}` on https://github.com/tailwindlabs/heroicons.com/blob/master/src/pages/index.js#L484 is not set correctly. https://github.com/tailwindlabs/heroicons/releases/tag/v0.4.0 seems to be the latest build.

**Comment by simonswiss** [comment]
Hey! 👋

The version `0.4.1` of heroicons got tagged [14 hours ago](https://github.com/tailwindlabs/heroicons/releases/tag/v0.4.1) and the version referenced in the heroicons.com website was [bumped to `0.4.1` "2 days ago"](https://github.com/tailwindlabs/heroicons.com/commit/82cdd1b432256108eaa07dc847ad8c4e4d1f44e4) (at least for me here in Australia 😅), so you probably caught the website right at an awkward time between the two?

The download link (which is [generated from the package.json version of heroicons](https://github.com/tailwindlabs/heroicons.com/blob/master/src/pages/index.js#L835)) is now working with `0.4.1`, I just tested.

We should probably make sure we release the new version of heroicons before updating the website 👍
