### ISSUE TITLE
I made a VS Code extension for Hero Icons

### ISSUE THREAD

**Issue by afzalsayed96** [tailwindlabs/heroicons.com#22]
I made a VS Code extension to add Hero Icons without leaving from code editor. The extension renders a webview of a [forked](https://github.com/afzalsayed96/heroicons.com) heroicons.com site.

![ezgif-6-d82027905ac9](https://user-images.githubusercontent.com/14029371/92354957-ec00f080-f100-11ea-8ea6-79a47287a198.gif)

[Here's](https://github.com/afzalsayed96/vscode-heroicons) the source code for the extension. I would love to hear any thoughts from the Tailwind Labs team

And here's the published extension: https://marketplace.visualstudio.com/items?itemName=afzalsayed96.heroicons

**Comment by PawelBorkar** [comment]
@afzalsayed96 So cool
