### ISSUE TITLE
Opt-in to TailwindCSS upcoming breaking change (removeDeprecatedGapUtilities)

### ISSUE THREAD

**Issue by HonkingGoose** [tailwindlabs/heroicons.com#31]
## Description of problem

When you run `yarn dev` TailwindCSS warns you:

```
risk - There are upcoming breaking changes: removeDeprecatedGapUtilities
risk - We highly recommend opting-in to these changes now to simplify upgrading Tailwind in the future.
risk - https://tailwindcss.com/docs/upcoming-changes
```

## From [TailwindCSS upcoming changes](https://tailwindcss.com/docs/upcoming-changes)

Tailwind v1.7.0 introduced new `gap-x-{n}` and `gap-y-{n}` utilities to replace the existing `col-gap-{n}` and `row-gap-{n}` utilities. We currently include both by default, but the old utilities will be removed in v2.0.

## Proposed fix

- [ ] Do a search in the website files and change the old `col-gap-{n}` and `row-gap-{n}` with their `gap-x-{n}` or `gap-y-{n}` equivalent.
- [ ] Check to ensure you're not changing the layout.
- [ ] Opt-in to the breaking change by adding the `removeDeprecatedGapUtilities` to the `future` section of `tailwind.config.js`.

```javascript
// tailwind.config.js
module.exports = {
  future: {
    removeDeprecatedGapUtilities: true,
  },
  // ...
}
```

**Comment by adamwathan** [comment]
Happy to accept a PR for this, probably less work than writing up the issue was 😅  Going to close as this isn't really a problem for us in practice and it's just our own little site, not an open source library or something other people are using.
